In [1]:
import numpy as np

In [2]:
def init_pop_bin(npop,N_items):
    return np.random.randint(0,2,(npop,N_items))

In [8]:
def intialize_W_V(maxwight,N_items):# W_V[0] is wights and W_V[1] is values 
    W_V=np.zeros((2,N_items))
    for i in range(len(W_V[0])):
        W_V[0][i]=np.random.randint(1,maxwight)
        W_V[1][i]=np.random.randint(1,N_items*N_items*2)
    return W_V
    

In [7]:
np.random.randint(10,50)

35

In [14]:
W_V=intialize_W_V(50,10)

In [15]:
W_V

array([[ 24.,  48.,   6.,  49.,  28.,   9.,  24.,  46.,  17.,  48.],
       [159.,  73.,  12., 108., 171.,  67.,  75.,  72.,   8., 190.]])

In [17]:
s=np.random.randint(0,2,(1,10))

In [18]:
s

array([[0, 0, 1, 1, 1, 0, 1, 0, 1, 1]])

In [20]:
W_V[0].shape

(10,)

In [22]:
s[0].shape

(10,)

In [23]:
W_V[0]*=s[0]

In [24]:
W_V

array([[  0.,   0.,   6.,  49.,  28.,   0.,  24.,   0.,  17.,  48.],
       [159.,  73.,  12., 108., 171.,  67.,  75.,  72.,   8., 190.]])

In [33]:
def crm_fit(crm,W_V):
    W_V_fit=[]
    for i in W_V:
        W_V_fit.append((crm*i).sum())
    return np.array(W_V_fit)

In [30]:
for i in W_V:
    
    print(s[0]*i)

[ 0.  0.  6. 49. 28.  0. 24.  0. 17. 48.]
[  0.   0.  12. 108. 171.   0.  75.   0.   8. 190.]


In [29]:
s[0]

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1])

In [36]:
crm_fit(s[0],W_V)

array([172., 564.])

In [43]:
def pop_fit(pop,W_V):
    pop_fits=[]
    for i in range(len(pop)):
        pop_fits.append(crm_fit(pop[i],W_V))
    return np.array(pop_fits)

In [38]:
pop=init_pop_bin(5,7)

In [39]:
wights_values=intialize_W_V(maxwight=20,N_items=7)

In [40]:
wights_values

array([[ 2., 11.,  8., 12., 13., 12., 12.],
       [95., 25.,  1., 72., 39., 13., 30.]])

In [41]:
pop

array([[1, 1, 0, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 0]])

In [105]:
fitts=pop_fit(pop,wights_values)

In [106]:
fits[:2]

array([[0., 0.],
       [0., 0.]])

In [107]:
fitts

array([[ 38., 189.],
       [ 45., 164.],
       [ 22., 126.],
       [ 35.,  68.],
       [ 20.,  14.]])

In [54]:
np.argmax(fits[:,1])

0

In [56]:
fits[0][0]

38.0

In [57]:
fits[0]=5

In [81]:
fits

array([[ 38., 189.],
       [ 45., 164.],
       [ 22., 126.],
       [ 35.,  68.],
       [ 20.,  14.]])

In [103]:
def get_best_fit(fits,max_wight):
    fits_temp=np.copy(fits)
    max_index_val=np.argmax(fits_temp[:,1])
    best_fit=0
    while fits_temp[max_index_val,0]>max_wight:
        fits_temp[max_index_val]=0
        max_index_val=np.argmax(fits_temp[:,1])
    best_fit=fits[max_index_val]
    return best_fit,max_index_val
    

In [109]:
get_best_fit(fitts,36)

(array([ 22., 126.]), 2)

In [110]:
get_best_fit(fitts,21)

(array([20., 14.]), 4)

In [111]:
fitts


array([[ 38., 189.],
       [ 45., 164.],
       [ 22., 126.],
       [ 35.,  68.],
       [ 20.,  14.]])

In [47]:
def binary_cross_over(tps,pcross):
    tow_childrens=np.zeros(tps.shape)
    if np.random.rand()<=pcross:
        cross_point=np.random.randint(1,tps.shape[1]-1)
        tow_childrens[0][0:cross_point]=tps[0][0:cross_point]
        tow_childrens[0][cross_point:]=tps[1][cross_point:]
        tow_childrens[1][0:cross_point]=tps[1][0:cross_point]
        tow_childrens[1][cross_point:]=tps[0][cross_point:]
    return tow_childrens

In [48]:
def bin_mute(cromosom,pmute):
    for i in range(len(cromosom)):
        if np.random.rand() <=pmute:
            if cromosom[i]==0:
                cromosom[i]=1
            else:
                cromosom[i]=0
    return cromosom

In [117]:
def tourment_selectian(pop,tour_size,fitness_values,maxwight):
    tow_parents=np.zeros((2,pop.shape[1]))
    for i in range(len(tow_parents)):
        slicer=np.random.randint(0,pop.shape[0]-tour_size)
        tour=pop[slicer:slicer+tour_size]
        fit=fitness_values[slicer:slicer+tour_size]
        
        best_fits,index_of_bsf=get_best_fit(fit,maxwight)
        tow_parents[i]=tour[index_of_bsf]
        
    return tow_parents
    

In [120]:
def runBinGA(n_pop,n_items,ngen,pcross,pmute,tour_size,max_wight):
    #intialize population 
    pop=init_pop_bin(n_pop,n_items)
    #intialize wights and values for every item 
    W_V=intialize_W_V(max_wight,n_items)
    #intialize best solution 
    best_solution=[]
    #intialize new pop
    ofsprings=np.zeros((pop.shape))
    
    #loop over generations to create final ofsprings
    for i in range(ngen):
        fits=pop_fit(pop,W_V)
        counter=0
        while counter<len(ofsprings):
            parents=tourment_selectian(pop,tour_size,fits,max_wight)#select two parents
            #get childrens from cross over 
            ch= binary_cross_over(parents,pcross)
            # mutation 
            for j in range(2):
                ch[j]=bin_mute(ch[j],pmute)
                
            ofsprings[counter]=ch[0]
            ofsprings[len(ofsprings)-counter-1]=ch[1]
            counter+=1
            
        
        ofspring_fit=pop_fit(ofsprings,W_V)
        best_fit_sol,index_of_bfs=get_best_fit(ofspring_fit,max_wight)
        best_solution.append(ofsprings[index_of_bfs])
        pop=ofsprings
    
  
    
    
    return best_solution                                       
                                 

In [121]:
runBinGA(n_pop=50,n_items=10,ngen=10,pcross=0.7,pmute=0.01,tour_size=10,max_wight=100)

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 0., 1., 0.])]