In [3]:
import numpy as np

In [4]:
def init_pop_bin(npop,N_items):
    return np.random.randint(0,2,(npop,N_items))

In [5]:
def intialize_W_V(maxwight,N_items):# W_V[0] is wights and W_V[1] is values 
    W_V=np.zeros((2,N_items))
    for i in range(len(W_V[0])):
        W_V[0][i]=np.random.randint(1,maxwight)
        W_V[1][i]=np.random.randint(1,N_items*N_items*2)
    return W_V
    

In [6]:
np.random.randint(10,50)

32

In [7]:
W_V=intialize_W_V(50,10)

In [8]:
W_V

array([[  4.,  27.,  29.,  22.,  32.,  29.,   9.,  33.,  48.,  21.],
       [138.,  73., 195., 192.,  27., 186.,  60., 126.,   3., 171.]])

In [9]:
s=np.random.randint(0,2,(1,10))

In [10]:
s

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 1]])

In [11]:
W_V[0].shape

(10,)

In [12]:
s[0].shape

(10,)

In [13]:
W_V[0]*=s[0]

In [14]:
W_V

array([[  4.,   0.,  29.,   0.,  32.,   0.,   9.,   0.,  48.,  21.],
       [138.,  73., 195., 192.,  27., 186.,  60., 126.,   3., 171.]])

In [15]:
def crm_fit(crm,W_V):
    W_V_fit=[]
    for i in W_V:
        W_V_fit.append((crm*i).sum())
    return np.array(W_V_fit)

In [16]:
for i in W_V:
    
    print(s[0]*i)

[ 4.  0. 29.  0. 32.  0.  9.  0. 48. 21.]
[138.   0. 195.   0.  27.   0.  60.   0.   3. 171.]


In [17]:
s[0]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [18]:
crm_fit(s[0],W_V)

array([143., 594.])

In [19]:
def pop_fit(pop,W_V):
    pop_fits=[]
    for i in range(len(pop)):
        pop_fits.append(crm_fit(pop[i],W_V))
    return np.array(pop_fits)

In [20]:
pop=init_pop_bin(5,7)

In [21]:
wights_values=intialize_W_V(maxwight=20,N_items=7)

In [22]:
wights_values

array([[14., 16., 17.,  8., 18., 18.,  6.],
       [41., 10., 55.,  6., 80., 39., 27.]])

In [23]:
pop

array([[1, 1, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 0]])

In [24]:
fitts=pop_fit(pop,wights_values)

In [25]:
fits[:2]

NameError: name 'fits' is not defined

In [26]:
fitts

array([[ 44.,  84.],
       [ 65., 137.],
       [ 72., 197.],
       [ 24.,  66.],
       [ 48.,  90.]])

In [27]:
np.argmax(fits[:,1])

NameError: name 'fits' is not defined

In [28]:
fits[0][0]

NameError: name 'fits' is not defined

In [29]:
fits[0]=5

NameError: name 'fits' is not defined

In [30]:
fits

NameError: name 'fits' is not defined

In [31]:
def get_best_fit(fits,max_wight):
    fits_temp=np.copy(fits)
    max_index_val=np.argmax(fits_temp[:,1])
    best_fit=0
    while fits_temp[max_index_val,0]>max_wight:
        fits_temp[max_index_val]=0
        max_index_val=np.argmax(fits_temp[:,1])
    best_fit=fits[max_index_val]
    return best_fit,max_index_val
    

In [32]:
get_best_fit(fitts,36)

(array([24., 66.]), 3)

In [33]:
get_best_fit(fitts,21)

(array([44., 84.]), 0)

In [34]:
fitts


array([[ 44.,  84.],
       [ 65., 137.],
       [ 72., 197.],
       [ 24.,  66.],
       [ 48.,  90.]])

In [35]:
def binary_cross_over(tps,pcross):
    tow_childrens=np.zeros(tps.shape)
    if np.random.rand()<=pcross:
        cross_point=np.random.randint(1,tps.shape[1]-1)
        tow_childrens[0][0:cross_point]=tps[0][0:cross_point]
        tow_childrens[0][cross_point:]=tps[1][cross_point:]
        tow_childrens[1][0:cross_point]=tps[1][0:cross_point]
        tow_childrens[1][cross_point:]=tps[0][cross_point:]
    return tow_childrens

In [36]:
def bin_mute(cromosom,pmute):
    for i in range(len(cromosom)):
        if np.random.rand() <=pmute:
            if cromosom[i]==0:
                cromosom[i]=1
            else:
                cromosom[i]=0
    return cromosom

In [37]:
def tourment_selectian(pop,tour_size,fitness_values,maxwight):
    tow_parents=np.zeros((2,pop.shape[1]))
    for i in range(len(tow_parents)):
        slicer=np.random.randint(0,pop.shape[0]-tour_size)
        tour=pop[slicer:slicer+tour_size]
        fit=fitness_values[slicer:slicer+tour_size]
        
        best_fits,index_of_bsf=get_best_fit(fit,maxwight)
        tow_parents[i]=tour[index_of_bsf]
        
    return tow_parents
    

In [38]:
def runBinGA(n_pop,n_items,ngen,pcross,pmute,tour_size,max_wight):
    #intialize population 
    pop=init_pop_bin(n_pop,n_items)
    #intialize wights and values for every item 
    W_V=intialize_W_V(max_wight,n_items)
    #intialize best solution 
    best_solution=[]
    #intialize new pop
    ofsprings=np.zeros((pop.shape))
    
    #loop over generations to create final ofsprings
    for i in range(ngen):
        fits=pop_fit(pop,W_V)
        counter=0
        while counter<int(len(ofsprings)/2):
            parents=tourment_selectian(pop,tour_size,fits,max_wight)#select two parents
            #get childrens from cross over 
            ch= binary_cross_over(parents,pcross)
            # mutation 
            for j in range(2):
                ch[j]=bin_mute(ch[j],pmute)
                
            ofsprings[counter]=ch[0]
            ofsprings[len(ofsprings)-counter-1]=ch[1]
            counter+=1
            
        
        ofspring_fit=pop_fit(ofsprings,W_V)
        best_fit_sol,index_of_bfs=get_best_fit(ofspring_fit,max_wight)
        best_solution.append(ofsprings[index_of_bfs])
        pop=ofsprings
    
  
    
    
    return best_solution                                       
                                 

In [39]:
runBinGA(n_pop=50,n_items=10,ngen=10,pcross=0.7,pmute=0.01,tour_size=10,max_wight=100)

[array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 0., 0., 0., 1., 0., 1., 0., 1.]),
 array([1., 1., 0., 0., 0., 1., 0., 1., 0., 1.]),
 array([1., 1., 0., 0., 0., 1., 0., 1., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 1.]),
 array([1., 1., 0., 0., 0., 1., 0., 1., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 1., 0., 1., 0., 1.])]