In [1]:
import numpy as np


# intialize population that is a number of random intial solutions 

In [118]:
def pop_intializer(n_cities,n_sols):
    arr=np.arange(1,n_cities+1)
    pop=np.zeros((n_sols,n_cities))
    for i in range(n_sols):
        np.random.shuffle(arr)
        pop[i]=arr
    return pop.astype(int)
    

# intialize distances between cities random too because i cant write them one by one make sense 

In [119]:
def dists_between_Cs(n_cities):# random intialzation for distances between evry two cities 
    dist=dict()
    defullt_arr=np.arange(1,n_cities+1)
    for i in range(1,len(defullt_arr)):
        for j in range(i,len(defullt_arr)+1):
            if i==j:
                continue
            else:
                dist[str(i)+"->"+str(j)]=np.random.randint(n_cities*n_cities*2)  
    return dist
    

In [120]:
pop ,dits=pop_intializer(5,5),dists_between_Cs(5)

# loop over distances that we intialized randomly to calculate the distance of solution that we wanna minimize it

In [136]:
def C_fit(crmsms,dist):
    fit_sum=0
    crmsms=crmsms.astype(int)
    for i in range(len(crmsms)-1):
        if (str(crmsms[i])+"->"+str(crmsms[i+1])) in dist:
            fit_sum+=dist[str(crmsms[i])+"->"+str(crmsms[i+1])]
        else:
            fit_sum+=dist[str(crmsms[i+1])+"->"+str(crmsms[i])]
    return fit_sum
    
    

In [137]:
"1->0" in dits

False

In [6]:
pop[3]

array([1, 3, 4, 5, 2])

In [122]:
dits

{'1->2': 6,
 '1->3': 9,
 '1->4': 0,
 '1->5': 19,
 '2->3': 4,
 '2->4': 7,
 '2->5': 30,
 '3->4': 17,
 '3->5': 28,
 '4->5': 39}

In [8]:
C_fit(pop[3],dits)

86

In [11]:
np.argmin(pop[0])

4

# loop over all pop to calculate every cromosom fitness

In [12]:
def pop_fits(pop,dists):
    fits=np.zeros((pop.shape[0],1))
    for i in range(pop.shape[0]):
        fits[i]=C_fit(pop[i],dists)
    return fits
        

In [13]:
fitness=pop_fits(pop,dits)

In [14]:
fitness


array([[ 64.],
       [138.],
       [ 92.],
       [ 86.],
       [ 69.]])

In [15]:
pop[0]

array([4, 5, 2, 3, 1])

In [16]:
dits

{'1->2': 47,
 '1->3': 2,
 '1->4': 27,
 '1->5': 2,
 '2->3': 22,
 '2->4': 29,
 '2->5': 24,
 '3->4': 44,
 '3->5': 43,
 '4->5': 16}

# tourment selection to detrmine the parents


In [17]:
def tourment_selectian(pop,tour_size,fitness_values):
    tow_parents=np.zeros((2,pop.shape[1]))
    for i in range(2):
        slicer=np.random.randint(0,pop.shape[0]-tour_size)
        tour=pop[slicer:slicer+tour_size]
        fit=fitness_values[slicer:slicer+tour_size]
        minindex_in_pop=np.argmin(fit)
        tow_parents[i]=tour[minindex_in_pop]
    return tow_parents

In [18]:
np.arange(1,5)

array([1, 2, 3, 4])

# order one selection 

In [139]:
def order_oneX(parents,WindowSize):
    cutP=np.random.randint(0,len(parents[1])-WindowSize)# minimum slice will be of two allels 
    children=np.zeros((1,len(parents[1])))
    children[0][cutP:cutP+WindowSize]=parents[0][cutP:cutP+WindowSize]
    
    start_of_x=cutP+WindowSize
    counter=start_of_x
    while True:
        if counter>=len(parents[1]):
            counter=0
        if start_of_x>=len(children[0]):
            start_of_x=0
        
        if (parents[1][counter] in children[0])==False:
            children[0][start_of_x]=parents[1][counter]
            counter+=1
            start_of_x+=1
        if (0 in children[0])==False:
            break 
        counter+=1
              
    return children.astype(int)
            
    
    

In [141]:
ch=order_oneX(pop[1:3],2)
ch

array([[5, 3, 1, 4, 2]])

In [96]:
def swap_mut(ch):
    r1=np.random.randint(0,len(ch[0]))
    r2=np.random.randint(0,len(ch[0]))
    while r1==r2:
        r2=np.random.randint(0,len(ch[0]))
    ch[0][r1],ch[0][r2]=ch[0][r2],ch[0][r1]
    return ch
    

In [98]:
ch

array([[2, 5, 3, 1, 4]])

In [100]:
swap_mut(ch)

array([[2, 4, 1, 3, 5]])

In [142]:
def TSP_GA(N_cities,N_in_sols,N_gen,tour_size):
    pop,dists=pop_intializer(N_cities,N_in_sols),dists_between_Cs(N_cities)
    ofsprings=np.zeros(pop.shape)
    best_sols=[]
    final_fits=[]
    for i in range(N_gen):
        fitness_values=pop_fits(pop,dists)
        counter=0
        while counter<len(ofsprings):
            parents=tourment_selectian(pop,tour_size,fitness_values)
            WindowSize=np.random.randint(2,int(N_cities/2))
            ch=order_oneX(parents,WindowSize)
            ofsprings[counter]=swap_mut(ch)
            counter+=1
        fit_ofspring=pop_fits(ofsprings,dists)#calculate fits of new generation that we generate from above while
        best_sols.append(ofsprings[np.argmin(fit_ofspring)])#get minimum distance of the all routs we generate
        final_fits.append(np.min(fit_ofspring))
        pop=ofsprings# set of springs as new population 
        #loop to last generation 
    return best_sols,
        
        
    

In [114]:
np.random.randint(2,5)

4

In [115]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [116]:
np.argmin(np.arange(5))

0

In [144]:
TSP_GA(10,10,4,3)

[array([ 8.,  1.,  5.,  4.,  2.,  9.,  7., 10.,  3.,  6.]),
 array([ 4.,  6.,  8.,  1.,  9.,  5.,  7., 10.,  3.,  2.]),
 array([ 2.,  5.,  4.,  7.,  1., 10.,  6.,  8.,  3.,  9.]),
 array([ 3.,  4.,  6.,  1.,  2., 10.,  9.,  5.,  7.,  8.])]