In [16]:
import numpy as np 

In [17]:
def intial_payoff(n,m):
    A=np.random.randint(-5,7, size=(n, m))
    B=np.random.randint(-5,7, size=(n, m))
    return A,B

In [18]:
A,B=intial_payoff(3,4)

In [19]:
A

array([[ 0,  1,  6,  1],
       [-3,  6,  3, -5],
       [ 1,  2,  0,  0]])

In [20]:
B

array([[ 1,  5,  1, -2],
       [ 6,  3,  1, -4],
       [ 2,  1, -4, -5]])

# checking dominants strategies 

In [21]:
B[:,0]>=B[:,1]

array([False,  True,  True])

In [22]:
A[0,:]>=A[1,:]

array([ True, False,  True,  True])

In [23]:
A[::-1]

array([[ 1,  2,  0,  0],
       [-3,  6,  3, -5],
       [ 0,  1,  6,  1]])

In [24]:
def Remove_All_domin(A,B):
    treger=np.copy(A)
    stop=0
    dominants=[]
    while True:

        if treger.shape != A.shape:
            treger=np.copy(A)
        else:
            stop+=1
        if stop==2:
            break
        elif B.shape==(1,1):
            break
        
        
       
        for i in range(len(A)):
            for j in range(len(A)):
                if i==j:
                    continue
                if (A[i]>A[j]).all():
                    print("Strategy",i)
                    print("stricly dominant A")
                    print("Strategy",j)
                    print("####")
                    dominants.append(j)
                elif (A[i]>A[j]).all():
                    print("Strategy",i)
                    print("weakly dominant A")
                    print("Strategy",j)
                    print("####")
                    dominants.append(j)


        A=np.delete(A,dominants,axis=0)
        B=np.delete(B,dominants,axis=0)
        dominants=[]
        for i in range(len(B[0])):
            for j in range(len(B[0])):
                if i==j:
                    continue
                if (B[:,i]>B[:,j]).all():
                    print("Strategy",i)
                    print("stricly dominant B")
                    print("Strategy",j)
                    print("####")
                    dominants.append(j)
                elif (B[:,i]>=B[:,j]).all():
                    print("Strategy",i)
                    print("weakly dominant B")
                    print("Strategy",j)
                    print("####")
                    dominants.append(j)

        A=np.delete(A,dominants,axis=1)
        B=np.delete(B,dominants,axis=1)

        print("############### A:")
        print(A)
        print("############### B:")
        print(B)
    print("After Remove Dominants: P1:",A)
    print("After Remove Dominants: P2:",B)
    return A,B

In [25]:
Remove_All_domin(A,B)

Strategy 0
weakly dominant B
Strategy 2
####
Strategy 0
stricly dominant B
Strategy 3
####
Strategy 1
stricly dominant B
Strategy 2
####
Strategy 1
stricly dominant B
Strategy 3
####
Strategy 2
stricly dominant B
Strategy 3
####
############### A:
[[ 0  1]
 [-3  6]
 [ 1  2]]
############### B:
[[1 5]
 [6 3]
 [2 1]]
Strategy 2
stricly dominant A
Strategy 0
####
Strategy 0
stricly dominant B
Strategy 1
####
############### A:
[[-3]]
############### B:
[[6]]
After Remove Dominants: P1: [[-3]]
After Remove Dominants: P2: [[6]]


/home/mohamed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:36: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
/home/mohamed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:37: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.


(array([[-3]]), array([[6]]))

In [26]:
A

array([[ 0,  1,  6,  1],
       [-3,  6,  3, -5],
       [ 1,  2,  0,  0]])

In [27]:
B

array([[ 1,  5,  1, -2],
       [ 6,  3,  1, -4],
       [ 2,  1, -4, -5]])

In [28]:
def find_nash(A,B):
    nashs=[]
    for i in range(len(A)):
        for j in range(len(A[0])):
            if (A[i][j]==np.max(A[:,j]))and(B[i][j]==np.max(B[i,:])):
                nashs.append((i,j))
            
    return nashs
    
    

In [14]:
np.argmax(B)

4

In [102]:
np.max(A[0])

6

In [29]:
find_nash(A,B)

[(2, 0)]

In [104]:
def calc_expected(A,B,x,y):
    U1=np.dot(x,np.dot(A,y))
    U2=np.dot(x,np.dot(B,y))
    
    return U1,U2

In [105]:
A

array([[-4, -1, -2,  6],
       [ 1, -3, -3,  0],
       [-4, -2, -1,  4]])

In [106]:
B

array([[-1,  5, -5,  1],
       [-5,  0,  1, -3],
       [ 6, -1,  6, -4]])

In [107]:
x=[0.2,0.3,0.5]
y=[0,0.25,0.5,0.25]

In [108]:
calc_expected(A,B,x,y)

(-0.6249999999999999, 0.6)

In [30]:
def find_trembling_hand(A,B):#is the point that eny player deviate from it must one of them lose and it's nash
    trem=[]
    
    

In [31]:
def positive_afine_transform(A,B):
    a=np.random.randint(0,max(A)+1)
    b=np.random.randint(0,max(A)+1)
    A=A*a+b
    a=np.random.randint(0,max(A)+1)
    b=np.random.randint(0,max(A)+1)
    B=B*a+b
    return A,B

In [34]:
def find_category(A):
    if A.shape==(2,2):
        A[:,0]-=A[1,0]
        A[:,1]-=A[1,1]
        if (A[0,0]>0) and (A[1,1]>0):
            print("category:II")
        elif (A[0,0]>0) and (A[1,1]<0):
            print("category:IV")
        elif (A[0,0]<0) and (A[1,1]>0):
            print("category:I")
        elif (A[0,0]<0) and (A[1,1]<0):
            print("category:III")
    else:
        print("please enter 2X2 payoff matrix.")

In [33]:
A

array([[ 3,  1,  6,  1],
       [ 0,  6,  3, -5],
       [ 4,  2,  0,  0]])